"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Pradyumna Kandi, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: prk599
"""

import sys
def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    encode = ""

    for i in range(key):
        row = i + 1
        cntr = i
        inc2 = i * 2
        inc1 = (key * 2 - 2) - inc2

        while cntr < len(string):
            if row == 1:
                encode += string[cntr]
                cntr += inc1
            elif row == key:
                encode += string[cntr]
                cntr += inc2
            else:
                encode += string[cntr]
                cntr += inc1
                if cntr >= len(string):
                    break
                encode += string[cntr]
                cntr += inc2


    return encode


def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    decode = [""] * len(string)
    idx = 0

    for i in range(key):
        row = i + 1
        cntr = i
        inc2 = i * 2
        inc1 = (key * 2 - 2) - inc2

        while cntr < len(string):
            if row == 1:
                decode[cntr] = string[idx]
                idx += 1
                cntr += inc1
            elif row == key:
                decode[cntr] = string[idx]
                idx += 1
                cntr += inc2
            else:
                decode[cntr] = string[idx]
                idx += 1
                cntr += inc1
                if cntr >= len(string):
                    break
                decode[cntr] = string[idx]
                idx += 1
                cntr += inc2

    return ''.join(decode)


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    filtered = ""
    for c in string:
        if c.isalpha():
            filtered += c.lower()
    return filtered


def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    base = ord(p)
    add = ord(s)
    letter = base + (add % 97)
    if letter > 122:
        letter -= 26
    return chr(letter)



def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    base = ord(p)
    add = ord(s)
    letter = add - base
    if letter < 0:
        letter += 26
    letter += 97
    return chr(letter)



def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    clean_string = filter_string(string)
    clean_phrase = filter_string(phrase)
    encode = ""

    l_string = len(clean_string)
    l_phrase = len(clean_phrase)

    for i in range(l_string):
        encode += encode_character(clean_phrase[i%l_phrase],clean_string[i])

    return encode


def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    clean_string = filter_string(string)
    clean_phrase = filter_string(phrase)
    decode = ""

    l_string = len(clean_string)
    l_phrase = len(clean_phrase)

    for i in range(l_string):
        decode += decode_character(clean_phrase[i%l_phrase],clean_string[i])

    return decode



def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # encrypt and print the encoded text using rail fence cipher

    # read encoded text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # encrypt and print the encoded text using Vigenere cipher

    # read the encoded text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # decrypt and print the plain text using Vigenere cipher
    words = []

    for line in sys.stdin:
        words.append(line.strip())
    print("Rail Fence Cipher")
    print()
    print("Plain Text:", words[0])
    print("Key:", words[1])
    print("Encoded Text:", rail_fence_encode(words[0], int(words[1]) ))
    print()
    print("Encoded Text:", words[2])
    print("Enter Key:", words[3])
    print("Decoded Text:", rail_fence_decode(words[2], int(words[3]) ))
    print()
    print("Vigenere Cipher")
    print()
    print("Plain Text:", words[4])
    print("Pass Phrase:", words[5])
    print("Encoded Text:", vigenere_encode(words[4], words[5]))
    print()
    print("Encoded Text:", words[6])
    print("Pass Phrase:", words[7])
    print("Decoded Text:", vigenere_decode(words[6], words[7]))




# Do NOT modify the following code.
if __name__ == "__main__":
    main()
